name: Clone-And-Post

on:
  workflow_dispatch:
    inputs:
      REPO_ADDY:
        description: 'repo link'
        required: true
        default: 'https://gitlab.com/kinguser981/neutron-clang-18.git'
      DEVICE_BRANCH:
        description: 'branch name (Optional)'
        required: true
        default: 'master'
      GITHUB_TOKEN:
        description: 'your github Access token (Optional)'
        required: true
        default: 'XXXXXXXXXXXXXXXXXXXXXXXXXX'
      EMPTY_REPO:
        description: 'your empty repo name on github (Optional)'
        required: true
        default: 'new-empty-repo.git'
      COMMIT_MESSAGE:
        description: 'your commit message (Optional)'
        required: true
        default: 'any commit message'

jobs:
  build:
    name: Cloning by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Downloading the Repository
      run: |
        git config --global user.email "Samuel Kendall"
        git config --global user.name "kinguser981@gmail.com"
        mkdir repo
        cd repo
        git clone ${{ github.event.inputs.REPO_ADDY }}

    - name: Push to GitHub
      run: |
          cd repo/*
          rm -rf .git
          git init
          git add .
          git commit -m "${{ github.event.inputs.COMMIT_MESSAGE }}"
          git branch -M ${{ github.event.inputs.DEVICE_BRANCH }}
          git remote add origin git@github.com:${{ github.actor }}/${{ github.event.inputs.EMPTY_REPO }}
          git remote set-url origin https://${{ github.actor }}:${{ github.event.inputs.GITHUB_TOKEN }}@github.com/${{ github.actor }}/${{ github.event.inputs.EMPTY_REPO }}
          git push -u origin ${{ github.event.inputs.DEVICE_BRANCH }}
